---
scenario:
  name: docker-ubuntu
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: true
platforms:
  - name: Ubuntu
    image: solita/ubuntu-systemd:18.04
    privileged: true
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: ../prepare.yml
    converge: ../playbook.yml

verifier:
  name: testinfra
  lint:
    name: flake8
  enabled: true
