# tasks file for ansible-cis-docker-benchmark
---

- name: "Section 1: Host Configuration"
  include_tasks: section_1.yml
  when: cdb_section_1|bool

- name: "Section 2: Docker Daemon Configuration"
  include_tasks: section_2.yml
  when: cdb_section_2|bool

- name: "Section 3: Docker Daemon Configuration Files"
  include_tasks: section_3.yml
  when: cdb_section_3|bool
