---
- name: Prepare
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: "Install packages for testing under docker"
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: "Add an Apt signing key, will not download if present"
      apt_key:
        id: 0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: "Add Docker APT repository"
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
        state: present

    - name: "Install latest docker-related packages"
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    - name: "Add /etc/docker/daemon.json"
      copy:
        dest: /etc/docker/daemon.json
        content: {}
        owner: root
        group: root
        mode: '0640'


    - name: "Restart docker"
      service:
        name: docker
        state: restarted

    - name: "Ensure rsyslog is listening on port 514 (needed for tests)"
      lineinfile:
        path: /etc/rsyslog.conf
        line: module(load="imtcp")
        state: present

    - name: "Ensure rsyslog is listening on port 514 (needed for tests)"
      lineinfile:
        path: /etc/rsyslog.conf
        line: input(type="imtcp" port="514" Address="127.0.0.1")
        state: present

    - name: "Restart rsyslogd"
      service:
        name: rsyslog
        state: restarted
