---
# handlers file for ansible-cis-docker-benchmark

- name: Reload auditd Rules
  service:
    name: auditd
    state: restarted

- name: Reload docker
  service:
    name: docker
    state: restarted